# Specifying Compose Specification Version
version: "3.8"

# Defining Services
services:
  server:
    container_name: notebook-server
    build:
      context: .
      dockerfile: docker/local.dockerfile
    image: bank-churn-notebook
    ports:
      - "8888:8888"